### PR TITLE
Changes priority class to system-cluster-critical to improve chances …

### PR DESCRIPTION
**Pull request by danibaeyens**
…to be correctly scheduled

This PR modifies the priority class of linkerd control plane to improve chances to be scheduled on situations where there is higher pressure on the node. As linkerd is a critical component on a cluster, having it broken can lead to services unable to properly communicate with each other, or falling back to unmeshed communication, which can create other issues.

## Checklist

- [ ] Automated test are working (for chart changes)
- [x] I am confident my changes don't break existing installations (for chart changes)
- [x] Changelog entry has been added

### CODE REVIEW

**Comment by Gacko** [comment]
@mcharriere Is this is a good default value? Because if so you could also propose this to upstream.

**Review by Gacko — APPROVED** [review]

**Review by Gacko — CHANGES_REQUESTED** [review]
@danibaeyens Could you please run [`helm-docs`](https://github.com/norwoodj/helm-docs) or at least update the default value listed in the [README.md](https://github.com/giantswarm/linkerd-control-plane-app/blob/main/helm/linkerd-control-plane/README.md)? Thank you very much!

**Comment by danibaeyens** [comment]
will do/check both!

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
@mcharriere Just merged the changes required to make external contribution work (fixed the values schema check).

**Review by mcharriere — APPROVED** [review]

**Comment by Gacko** [comment]
Seems the CircleCI chart tests are required for this PR by GitHub repository configuration but not triggered by CircleCI configuration inside the repository.

@mcharriere Could you have a look at this?

**Comment by mcharriere** [comment]
Hm, it seems we don't allow forks to trigger CircleCI. Unfortunately it's not granular enough to allow certain forks, it's just on or off.

image

**Comment by Gacko** [comment]
So we either force merge or enable it temporarily.

**Comment by mcharriere** [comment]
I've enabled it. @danibaeyens could you push a commit? so CircleCI can be triggered.

**Comment by mcharriere** [comment]
Thanks @danibaeyens for your contributions. We still need to sort out some things with our CI. Because of that, I created another PR with your commit and will close this one.

**Pull request closed without merging**
